version: '3.9'
volumes:
  pg_data: {}
  mage_data: {}
services:
  mage:
    image: repository.dimas-maryanto.com:8086/mageai/mageai:0.7.99
    command: ['/app/run_app.sh', 'mage', 'start', 'satu_data']
    ports:
      - "6789:6789"
    depends_on:
      - postgres
    environment:
      - MAGE_DATABASE_CONNECTION_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - mage_data:/home/src
  postgres:
    image: repository.dimas-maryanto.com:8086/postgres:15.1
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    volumes:
      - pg_data:/var/lib/postgresql/data
